// scripts/copy/registry.mjs

export const FIGMA_FILE = 'VCjqlGu9kQVy2i5nqDxKqa'
export const FIGMA_BASE = `https://www.figma.com/design/${FIGMA_FILE}/Exploration-pt-II?node-id=`

export const SPREADSHEET_ID = '1AvNQLyVvbK1Xj-RSN-KL76LkIMxxL2SvyXgWNobnkL0'

export const HEADERS = [
  'ID',
  'Section',
  'Screen',
  'Segment',
  'Copy Type',
  'Content',
  'Status',
  'Notes',
  'Figma Link',
  'Key',
  'Variables',
  'Condition',
  'File',
  'Line',
  'Storage',
]

export const SCREEN_NAMES = {
  nav: 'Navigation Rail',
  intro: 'Welcome Intro',
  'create-plan': 'Meet Nyla',
  welcome: "Let's Get Started",
  profile: 'Profile Review',
  targets: 'Your Targets',
  'goals-intro': 'Goals Introduction',
  'advisor-vision': 'Your Vision',
  direction: 'Practice Direction',
  'fyc-target': 'FYC Target',
  'activity-target': 'Activity Targets',
  'outside-work': 'Life Outside Work',
  'growth-intro': 'Business Introduction',
  'progress-areas': 'Growth Areas',
  'time-pulls': 'Time Drains',
  'time-open': 'Biggest Time Drain',
  'clients-intro': 'Clients Introduction',
  'client-signals': 'Client Signals',
  'client-activities': 'Client Priorities',
  'client-conversations': 'Client Conversations',
  'stay-in-front': 'Staying Connected',
  'life-events': 'Life Event Response',
  plan: 'Your Plan',
  processing: 'Processing Animation',
  'plan-rail': 'Plan Sidebar',
  hero: 'Hero Section',
  'featured-card': 'Featured Priority Card',
  'opportunity-card': 'Opportunity Card',
}

export const SECTION_NAMES = {
  nav: 'Navigation',
  intro: 'Welcome',
  'create-plan': 'Introduction',
  welcome: 'Introduction',
  profile: 'Profile',
  targets: 'Profile',
  'goals-intro': 'Goals',
  'advisor-vision': 'Goals',
  direction: 'Goals',
  'fyc-target': 'Goals',
  'activity-target': 'Goals',
  'outside-work': 'Goals',
  'growth-intro': 'Business',
  'progress-areas': 'Business',
  'time-pulls': 'Business',
  'time-open': 'Business',
  'clients-intro': 'Clients',
  'client-signals': 'Clients',
  'client-activities': 'Clients',
  'client-conversations': 'Clients',
  'stay-in-front': 'Clients',
  'life-events': 'Clients',
  plan: 'Plan',
  processing: 'Plan',
  'plan-rail': 'Plan',
  hero: 'Briefing',
  'featured-card': 'Briefing',
  'opportunity-card': 'Action Board',
}

export const FIGMA_FRAMES = {
  nav: '524-2023',
  intro: '842-12468',
  'create-plan': '524-2023',
  welcome: '524-2537',
  profile: '524-2537',
  targets: '524-2752',
  'goals-intro': '524-2537',
  'advisor-vision': '524-2979',
  direction: '524-3208',
  'fyc-target': '524-2266',
  'activity-target': '524-3437',
  'outside-work': '524-3648',
  'growth-intro': '524-5692',
  'progress-areas': '524-5692',
  'time-pulls': '524-5907',
  'time-open': '524-6122',
  'clients-intro': '524-6368',
  'client-signals': '524-6368',
  'client-activities': '524-6621',
  'client-conversations': '524-6368',
  'stay-in-front': '524-6621',
  'life-events': '524-6873',
  plan: '524-9889',
  processing: '524-9889',
  'plan-rail': '524-5692',
  hero: '895-3701',
  'featured-card': '895-3701',
  'opportunity-card': '895-3701',
}
