import type { SegmentCode } from '@/data/advisorSegments'

/* Per-segment daily briefing content. Mirrors the structure of Zee's
 * NYL360_AdvisorBriefing_v2.html — bottom-line first, then action-required,
 * then schedule, then signals. Different advisor profiles surface different
 * threads so the briefing reflects the onboarding answers.
 *
 * For the demo we hand-author three coherent briefings (Marcus / Priya / Jordan).
 * In production these would be generated by the OS from book data, calendar
 * data, and the advisor's stated preferences. */

export type CoSAction = {
  label: string
  prompt?: string
  freeform?: boolean
  /* When set, the chip drills into ActionDeepDive's generative-UI canvas for
   * this client / scenario (e.g. 'helena-1', 'janet', 'tom-anderson'). */
  canvasId?: string
}

export type CardDetails = {
  analysis: string
  insight: string
  recommendation: string
  followup?: string
  suggestedActions?: CoSAction[]
}

export type UrgentItem = {
  id: string
  title: string
  body: string
  meta: string
  badge?: { label: string; tone: 'urgent' | 'monitor' | 'opportunity' }
  details?: CardDetails
  defaultOpen?: boolean
  actionPrompt?: string
  /* Outreach row — phone number and CTA label shown at the bottom of the card */
  phone?: string
  outreachCta?: string
  /* Priority tags rendered below the body */
  priorityTags?: string[]
}

export type ScheduleItem = {
  id: string
  time: string
  duration?: string
  title: string
  body: string
  /* Drives the timeline dot color + optional badge. */
  status: 'admin' | 'ready' | 'needsPrep' | 'wrap'
  /* When set, clicking the item opens the per-meeting brief (pre-meeting view). */
  meetingId?: string
}

export type ClientSignal = {
  id: string
  pip: 'red' | 'amber' | 'green'
  title: string
  body: string
  action: string
  badge: { label: string; tone: 'urgent' | 'monitor' | 'opportunity' }
  /* Optional rich expansion + Nyla actions. */
  details?: CardDetails
  defaultOpen?: boolean
  /* When set, the "→ action" inline link drops into CollabSpace with this prompt. */
  actionPrompt?: string
}

export type PaceStat = {
  label: string
  value: string
  sub: string
  tone: 'good' | 'warn' | 'neutral'
}

export type AutonomousItem = {
  id: string
  label: string
  meta: string
  /* Prompt that opens in CollabSpace when the row's "open in chief of staff"
   * chip is tapped. Only used as a fallback / secondary action — the row
   * itself expands inline now. */
  actionPrompt?: string
  /* Inline expansion shown when the row is tapped. Lets the advisor see what
   * the OS actually did without leaving the briefing. */
  expand?: {
    summary: string
    bullets?: string[]
    chips?: { label: string; prompt: string }[]
  }
}

/* A priority card on the daily briefing — replaces the old urgent+signals+pace
 * split. Each one is a single read-and-act observation. */
export type Priority = {
  id: string
  headline: string
  /* Substring inside `headline` to render in red (e.g. "underwriting for 11 days"). */
  highlight?: string
  sub?: string
  badge?: { label: string; tone: 'urgent' | 'monitor' | 'opportunity' | 'needsPrep' | 'high' | 'ready' }
  /* When set, clicking the meeting CTA inside the expanded card opens that
   * meeting's pre-meeting brief. */
  meetingId?: string
  /* Rich content shown when the card is expanded — Analysis / Insight /
   * Recommendation columns + a soft follow-up strip and optional suggested
   * action chips that drop into the CollabSpace. */
  details?: {
    analysis: string
    insight: string
    recommendation: string
    followup?: string
    suggestedActions?: CoSAction[]
  }
  /* When true, the card starts open on first render. Default = first priority. */
  defaultOpen?: boolean
}

/* Advisor-centric opportunity stat — drives the fitness-tracker style ring at
 * the top of the briefing. Per Zee: the read should be about the advisor's
 * goal and what's possible today, not any one client. */
export type OpportunityToday = {
  /* "$5,400 in FYC is sitting on your desk today." — the motivating one-liner. */
  fycInPlayLabel: string
  /* Numeric FYC achievable today across the priority threads. */
  fycInPlayValue: number
  /* Position on the year — drives the ring fill. */
  fycToDateLabel: string  /* "$92,400 of $122,000" */
  percentToGoal: number   /* 0–100 */
  /* "Two more closes today and you cross 80%." — the close-the-ring nudge. */
  ringNudge: string
  /* Optional secondary stat — a meaningful streak or motion. */
  streak?: string         /* "9 days in a row at >80% pace" */
}

export type DailyBriefing = {
  /* Header strip */
  firstName: string
  council: string
  location: string
  tenureLabel: string  /* "Year 16 · 633 clients" */
  /* Hero strip */
  date: { weekday: string; monthDay: string }
  dateLabel: string                  /* "Today  |  Thu, May 28" — shown in the ribbon */
  generatedAt: string
  /* Fitness-tracker style advisor opportunity (top motivator). */
  opportunityToday: OpportunityToday
  /* Magazine headline + optional red highlight inside it */
  headline: string
  headlineHighlight?: string
  /* Compact one-line summary directly under the headline (optional) */
  summary: string
  /* Curated TODAY'S PRIORITIES list. */
  priorities: Priority[]
  /* Old fields retained for the secondary horizons (week/month/etc.) that still
   * reference them — kept here so other surfaces don't break. */
  bottomLine: string
  urgent: UrgentItem[]
  schedule: ScheduleItem[]
  signals: ClientSignal[]
  pace: PaceStat[]
  autonomous: AutonomousItem[]
  /* Inline note acknowledging WHY the briefing leads with what it does — pulled
   * from the advisor's onboarding-stated priorities. */
  whyThisOrder: string
}

/* ----------------------------------------------------------------------------
 * Marcus T. — cs-leading (the briefing shown in Zee's screenshot)
 * -------------------------------------------------------------------------- */
const marcus: DailyBriefing = {
  firstName: 'Marcus',
  council: 'Executive Council',
  location: 'Queens NY',
  tenureLabel: 'Year 16 · 633 clients',
  date: { weekday: 'Thu', monthDay: 'May 28' },
  dateLabel: 'Today  |  Thursday, May 28',
  generatedAt: 'Briefing ready · 8:02 AM',
  opportunityToday: {
    fycInPlayLabel: '$6,000 in FYC is sitting on your desk today.',
    fycInPlayValue: 6000,
    fycToDateLabel: '$92,400 of $122,000',
    percentToGoal: 76,
    ringNudge: 'Close two threads today and you cross 80% — Cabinet pace.',
    streak: '9 days in a row above 80% pace',
  },
  headline: "Here's a couple of quick actions to set you up for the week — start by clearing the lapse risk",
  headlineHighlight: 'clearing the lapse risk',
  summary: '0/3 completed · As of 9:33 AM',
  priorities: [
    {
      id: 'anderson',
      headline: 'Tom Anderson has been sitting at underwriting for 11 days on a missing form. One 10-minute call clears it.',
      highlight: 'underwriting for 11 days',
      badge: { label: 'Urgent', tone: 'urgent' },
      defaultOpen: true,
      details: {
        analysis:
          "Whole life app stalled at underwriting due to a missing APS medical form and Tom hasn't received the request.",
        insight:
          'This is a system failure, not a client failure since the form was never sent. One resend resolves it.',
        recommendation:
          'Call Tom Anderson to set expectations, then resend APS request via Sales Central.',
        followup: "You'll hit $4,200 FYC if this closes.",
        suggestedActions: [
          { label: 'Review the issue', prompt: "Walk me through Tom Anderson's stall and what's actually blocking the APS resend." },
          { label: 'View underwriting timeline', prompt: "Show me Tom Anderson's underwriting timeline from submission to today." },
          { label: 'Something else…', freeform: true },
        ],
      },
    },
    {
      id: 'clarke',
      headline: 'Prepare for Emma Clarke\'s annual review at 11:00 AM',
      sub: '12-year client · WL + term + investment · pre-meeting brief loaded',
      badge: { label: 'Prep ready', tone: 'ready' },
      meetingId: 'clarke',
    },
    {
      id: 'lau',
      headline: "Patricia Lau's UL policy lapses in 2 days — payment not received",
      sub: 'Day 28 of 30 · $1,800 FYC reversal risk',
      badge: { label: 'Urgent', tone: 'urgent' },
    },
    {
      id: 'okafor',
      headline: 'Derek Okafor prospect discovery at 2:30 PM — confirm meeting first',
      sub: 'Referred by Clarke · business owner, age 44, no current life coverage',
      badge: { label: 'Need to prep', tone: 'needsPrep' },
      meetingId: 'okafor',
    },
    {
      id: 'clarke-referral',
      headline: "Emma's business partner may need coverage — listen for the second name at close",
      sub: 'Opportunity surfaces in today\'s annual review',
      badge: { label: 'Opportunity', tone: 'opportunity' },
    },
    {
      id: 'holloway',
      headline: "James Holloway turns 45 in six months — WL age-change deadline approaching",
      sub: 'Add to next-week contact list',
      badge: { label: 'Monitor', tone: 'monitor' },
    },
  ],
  bottomLine:
    "Today is a revenue day — one close opportunity and one annual review. The Anderson application has been pending 11 days on a missing medical form; that is your highest-leverage 10 minutes this morning. The Clarke meeting this afternoon has everything loaded. Don't let Anderson slide into week 3.",
  urgent: [
    {
      id: 'sandra-kim-lapse',
      title: 'Call Eric Ellis a lead from NYL.com to introduce yourself',
      body: "Completing this within the next 30 minutes gives you a 75% higher chane of closing the deal",
      meta: 'Prioritize existing clients · Boost FYC',
      badge: { label: 'NEW LEAD', tone: 'opportunity' },
      defaultOpen: false,
      phone: '(917) 625-4843',
      outreachCta: 'Plan a call',
      priorityTags: ['Lead', 'Potential High FYC'],
      actionPrompt: "Sandra Kim's WL policy is 14 days past due — draft a call script to reactivate the policy before it lapses.",
      details: {
        analysis: "Sandra's whole life policy payment is 14 days overdue. She has a 30-day grace period — 16 days remain.",
        insight: "Sandra has been a client since 2021 with a strong payment history. This is likely an oversight, not a cancellation intent.",
        recommendation: "Call before 10AM today. Lead with the policy and grace period deadline — skip the warmup. Have the payment link ready.",
        followup: "Resolving this protects $1,800 in FYC from chargeback this month.",
        suggestedActions: [
          { label: 'Draft call script', prompt: "Draft a short call script for Sandra Kim — WL payment past due, 16 days left in grace period. Direct and warm." },
          { label: 'Draft text', prompt: "Draft a text to Sandra Kim about her WL payment being past due. Friendly but clear about the deadline." },
          { label: 'Something else…', freeform: true },
        ],
      },
    },
    {
      id: 'laura-mendez-appt',
      title: "Contact Laura Mendez about her new home coverage and to add an uninsured spouse.",
      body: "This appointment gap spans one close per week. A short conversation here covers a $3,500 FYC opportunity.",
      meta: 'Qualified appointment · New coverage need',
      badge: { label: 'Qualified appt first', tone: 'opportunity' },
      priorityTags: ['Grow new clients', 'Boost FYC'],
      outreachCta: 'Book time',
      actionPrompt: "Help me prepare a quick outreach to Laura Mendez about home coverage and adding her spouse to her policy.",
      details: {
        analysis: "Laura purchased a new home 6 weeks ago. Her current policy doesn't cover the new property and her spouse is uninsured.",
        insight: "Home purchase triggers strong receptivity to coverage conversations. The timing is ideal.",
        recommendation: "Reach out this week. Lead with the home congratulations, pivot to coverage gap naturally.",
        suggestedActions: [
          { label: 'Draft outreach', prompt: "Draft a short outreach to Laura Mendez — congrats on the new home, mention coverage gap, propose a quick call." },
          { label: 'Something else…', freeform: true },
        ],
      },
    },
  ],
  schedule: [
    {
      id: 'admin',
      time: '9:00 AM',
      title: 'Office open / admin block',
      body: 'Anderson follow-up call, inbox triage, pipeline review. Target: clear the APS hold before 10.',
      status: 'admin',
    },
    {
      id: 'clarke',
      time: '11:00 AM',
      duration: '60 MIN',
      title: 'Emma Clarke — Annual Review',
      body:
        '12-year client, WL + term + investment account. Key agenda: beneficiary update (catch before she notices), fee-based rollover conversation ($210K), college funding gap. See pre-meeting brief for full pack.',
      status: 'ready',
      meetingId: 'clarke',
    },
    {
      id: 'okafor',
      time: '2:30 PM',
      duration: '60 MIN',
      title: 'Derek Okafor — Prospect discovery',
      body:
        'Referred by Clarke. Business owner, age 44, no current life coverage. Target: term + DI conversation. Confirm meeting — he was only verbal-committed.',
      status: 'needsPrep',
      meetingId: 'okafor',
    },
    {
      id: 'wrap',
      time: '4:30 PM',
      title: 'End-of-day wrap',
      body: 'Log meeting notes, queue follow-ups, update pipeline. Flag Okafor for Concierge scheduling.',
      status: 'wrap',
    },
  ],
  signals: [
    {
      id: 'lau',
      pip: 'red',
      title: 'Patricia Lau — policy lapse warning (day 28 of 30)',
      body: 'UL policy. Premium payment not received. Two days before lapse. Lapse = $1,800 FYC reversal risk plus relationship damage.',
      action: 'Call today or queue automated payment reminder via GuideMe',
      badge: { label: 'Day 28/30', tone: 'urgent' },
      defaultOpen: true,
      actionPrompt: "Help me decide whether to call Patricia Lau directly or queue an automated payment reminder via GuideMe.",
      details: {
        analysis: 'UL premium overdue for 28 of 30 days. Patricia paid late twice in the last 12 months but always recovered after a personal call.',
        insight: 'Auto-reminders work for first-time slips; not for the third. This needs a real call — the lapse risk is $1,800 FYC plus relationship damage.',
        recommendation: 'Call today before noon. If voicemail, send a personal text with the payment link and follow up by EOD.',
        followup: 'Cure rate after a personal call: 92% vs. 51% for automated reminder.',
        suggestedActions: [
          { label: 'Draft the call script', prompt: 'Draft a 60-second call script for Patricia Lau — empathetic, focused on the missed payment without sounding like collections.' },
          { label: 'Queue the GuideMe reminder', prompt: 'Queue an automated payment reminder for Patricia Lau via GuideMe and set a 24-hour follow-up alert.' },
          { label: 'Something else…', freeform: true },
        ],
      },
    },
    {
      id: 'holloway',
      pip: 'amber',
      title: 'James Holloway — half birthday alert',
      body: 'Turns 45 in 6 months. WL age-change deadline approaching — rate locks now or steps up at 45.',
      action: 'No action today; add to next-week contact list',
      badge: { label: 'Monitor', tone: 'monitor' },
      actionPrompt: "Add James Holloway to next week's contact list and queue a WL age-change conversation talking point.",
    },
    {
      id: 'clarke-referral',
      pip: 'green',
      title: 'Clarke meeting — second referral opportunity',
      body: "Emma mentioned her business partner may also need coverage. Look for a second name at the natural close of the annual review.",
      action: 'Prepare referral ask at close — the mood after the beneficiary catch will be right',
      badge: { label: 'Opportunity', tone: 'opportunity' },
      actionPrompt: "Draft a referral ask I can use at the natural close of Emma Clarke's annual review — about her business partner.",
    },
  ],
  pace: [
    { label: 'FYC this month',         value: '$18.4K', sub: 'of $22K target',              tone: 'warn' },
    { label: 'Appointments this week', value: '2 of 4', sub: '2 remaining',                 tone: 'neutral' },
    { label: 'Open cases',             value: '7',      sub: '1 urgent (Anderson)',         tone: 'warn' },
    { label: 'Council pace',           value: 'On track', sub: 'Executive Council',          tone: 'good' },
  ],
  autonomous: [
    { id: 'a1', label: 'Resent Anderson APS reminder',   meta: 'Sales Central · 7:48 AM',
      actionPrompt: 'Show me what was sent to Tom Anderson — the APS reminder, when, and whether anything else should follow.',
      expand: {
        summary: 'Re-sent the APS medical form request to Tom Anderson via Sales Central with a follow-up SMS scheduled if not signed by 9:00 AM.',
        bullets: [
          'Email subject: "One last form to wrap your application"',
          'Pre-filled with the carrier portal link · expires in 14 days',
          'SMS fallback queued for 9:00 AM if no e-sign event by then',
          'Underwriter notified the resend is in-flight',
        ],
        chips: [
          { label: 'View what was sent', prompt: "Show me the exact email + SMS the OS sent to Tom Anderson this morning — verbatim." },
          { label: 'Add a personal call', prompt: "Draft a 60-second personal call script for Tom Anderson to back up the APS resend." },
        ],
      },
    },
    { id: 'a2', label: 'Assembled Clarke meeting pack',  meta: 'Pre-meeting brief · 8:02 AM',
      actionPrompt: "Walk me through what was put into Emma Clarke's pre-meeting pack and where the source data came from.",
      expand: {
        summary: "Built Emma Clarke's full annual-review brief — beneficiary catch, 401(k) rollover, and college funding ready to lead with.",
        bullets: [
          'Pulled household + product data from last review (Mar 2025)',
          'Flagged: beneficiary not updated since 2012 (ex-husband still primary)',
          '$210K stranded 401(k) re-surfaced from last year\'s notes',
          'College funding math refreshed against the new 14-month timeline',
        ],
        chips: [
          { label: 'Open the brief', prompt: 'Open the Emma Clarke pre-meeting brief.' },
          { label: 'Draft talking points', prompt: 'Draft my opening talking points for the Emma Clarke meeting based on the pre-meeting brief.' },
        ],
      },
    },
    { id: 'a3', label: 'Queued Lau payment reminder',    meta: 'GuideMe · queued for 9:00 AM send',
      actionPrompt: "Show me the Patricia Lau payment reminder queued in GuideMe — I want to see it before it sends and decide if I should call instead.",
      expand: {
        summary: 'Queued a GuideMe payment reminder for Patricia Lau\'s UL policy (day 28 of 30). You can hold it and call instead.',
        bullets: [
          'Channel: GuideMe SMS + email · personalized with policy + payment link',
          'Send time: 9:00 AM · cancellable up to that point',
          'Historical cure rate after personal call: 92% vs. 51% for auto-reminder',
          'Recommend a personal call given two prior late payments in 12 months',
        ],
        chips: [
          { label: 'Hold the auto-send', prompt: 'Hold the Patricia Lau GuideMe send. I want to call her directly.' },
          { label: 'Draft the call script', prompt: 'Draft a 60-second empathetic call script for Patricia Lau about the missed UL premium.' },
        ],
      },
    },
    { id: 'a4', label: 'Triaged 23 inbox items',         meta: 'Concierge · filed overnight',
      actionPrompt: 'Show me the 23 inbox items triaged overnight — what got routed where, what was auto-replied, and what still needs me.',
      expand: {
        summary: 'Concierge sorted 23 overnight inbox items. 18 routed/auto-replied, 5 await your eyes.',
        bullets: [
          '11 client confirmations · auto-acknowledged',
          '4 newsletter unsubscribes · filed to CRM',
          '3 carrier updates · routed to Sales Central queue',
          '5 items flagged for you — referral from Maria Garcia is the standout',
        ],
        chips: [
          { label: 'Show me the 5 flagged items', prompt: 'Pull up the 5 inbox items the Concierge flagged for me this morning.' },
          { label: 'Reply to Maria Garcia', prompt: 'Draft a reply to the referral note from Maria Garcia — warm, brief, ask for the connection.' },
        ],
      },
    },
    { id: 'a5', label: 'Refreshed pipeline state',       meta: '7 open cases · 1 stuck on client docs',
      actionPrompt: 'Walk me through the 7 open cases — which one is stuck on client docs and what the next move is on each.',
      expand: {
        summary: '7 open cases re-scored. Anderson is the only one stuck — everything else has a clear next step.',
        bullets: [
          'Anderson · UW hold · day 11 · APS resend in flight',
          'Clarke · annual review today · pack ready',
          'Okafor · discovery today · confirm in writing',
          '4 healthy cases moving on cadence — no action needed',
        ],
        chips: [
          { label: 'Show pipeline detail', prompt: 'Walk me through every case in the pipeline right now — status, next step, est. FYC.' },
          { label: 'What changed overnight', prompt: 'What changed in my pipeline overnight? Surface only the deltas.' },
        ],
      },
    },
  ],
  whyThisOrder:
    "You told the OS lapse & at-risk alerts and pipeline items come first. Anderson hits both.",
}

/* ----------------------------------------------------------------------------
 * Priya M. — hl-accelerating
 * -------------------------------------------------------------------------- */
const priya: DailyBriefing = {
  firstName: 'Priya',
  council: 'No Council yet',
  location: 'Astoria NY',
  tenureLabel: 'Year 14 · 303 clients',
  date: { weekday: 'Thu', monthDay: 'May 28' },
  dateLabel: 'Today  |  Thursday, May 28',
  generatedAt: 'Briefing ready · 7:48 AM',
  opportunityToday: {
    fycInPlayLabel: '$8,200 in FYC is in play today.',
    fycInPlayValue: 8200,
    fycToDateLabel: '$22,600 of $84,000',
    percentToGoal: 27,
    ringNudge: 'One holistic conversation today moves your monthly pace from 27% to 38%.',
    streak: 'Holistic-talk-track readiness: 100%',
  },
  headline: "Open Helena's holistic chapter at 10:30 — the move your plan has been waiting for.",
  headlineHighlight: "Open Helena's holistic chapter at 10:30",
  summary: '2 items require your attention · 1 client meeting today · 1 holistic opening this week',
  priorities: [
    {
      id: 'helena',
      headline: 'Helena Garcia just turned 58 and is engaging with retirement content. Park morning prep until 10:30, then make the call.',
      highlight: 'retirement content',
      badge: { label: 'Opportunity', tone: 'opportunity' },
      defaultOpen: true,
      details: {
        analysis:
          'Helena just crossed the pre-60 milestone. Three retirement-readiness articles opened in 7 days; her engagement score jumped from 23 to 41. Last touched 5 months ago.',
        insight:
          "This is the holistic opening you've been waiting for. The window for retirement planning conversations is widest in the first 30 days of a milestone like this — and Helena flagged it herself through her behavior.",
        recommendation:
          'Draft a warm reconnection that frames the milestone, not the rate. Run the holistic talk-track drill first; aim for a 10:30 AM call.',
        followup: 'You said holistic openings and life events matter most. This is both.',
        suggestedActions: [
          { label: 'Draft the reconnection', canvasId: 'helena-1', prompt: "Draft a warm reconnection to Helena Garcia framed around the pre-60 milestone, not the rate." },
          { label: 'Run the holistic drill', canvasId: 'helena-2', prompt: "Run the holistic talk-track drill for the Helena Garcia call." },
          { label: 'Something else…', freeform: true },
        ],
      },
    },
    {
      id: 'patel',
      headline: "Leela Patel's annual review at 11:00 AM — cross-sell entry point identified",
      sub: 'Household grew · $1.2M term right-sized to a smaller household · education funding angle',
      badge: { label: 'Prep ready', tone: 'ready' },
      meetingId: 'patel',
    },
    {
      id: 'janet',
      headline: 'Janet Henderson moved to a coastal household — coverage gap on the new property',
      sub: '30-day post-move window · review pack queued by Strategist',
      badge: { label: 'Monitor', tone: 'monitor' },
    },
    {
      id: 'tom-stall',
      headline: 'Tom Anderson application stalled, day 11 — underwriting hold on a missing APS',
      sub: 'Resend via Sales Central today; this kills momentum on close',
      badge: { label: 'Urgent', tone: 'urgent' },
    },
    {
      id: 'drill',
      headline: 'Holistic talk-track drill loaded for 1:00 PM',
      sub: 'Strategist queued the Helena prep card · 5-min run before the call',
      badge: { label: 'Need to prep', tone: 'needsPrep' },
    },
  ],
  bottomLine:
    "Today opens with a holistic conversation already inside your book. Helena Garcia just turned 58 and has been engaging with retirement content — this is the moment you've been waiting for. Park the morning prep until 10:30, then make the call. Janet's coverage review is the second high-leverage move this week.",
  urgent: [
    {
      id: 'helena',
      title: 'Helena Garcia — retirement-readiness window opens',
      body:
        'Turned 58 in March. Three retirement-content opens this week. Last touched 5 months ago. The pre-60 window for holistic planning is open and unprompted — this is the move you flagged in onboarding.',
      meta: 'Action: Draft a warm reconnection · Frame the milestone, not the rate · Suggested time: 10:30 AM',
      badge: { label: 'Act today', tone: 'urgent' },
      defaultOpen: true,
      actionPrompt: "Open Helena Garcia's retirement-readiness window — walk me into a warm reconnection that frames the milestone, not the rate.",
      details: {
        analysis: 'Helena turned 58 in March. Three retirement-content articles opened in 7 days. Engagement score 23 → 41. Last touched 5 months ago.',
        insight: "This is the holistic opening you've been waiting for. The pre-60 planning window is widest in the first 30 days of a milestone like this, and Helena flagged it herself through her behavior.",
        recommendation: 'Draft a warm reconnection that opens with the milestone, not the rate. Run the holistic talk-track drill first. Aim for a 10:30 AM call.',
        followup: 'You said holistic openings and life events matter most. This is both.',
        suggestedActions: [
          { label: 'Draft the reconnection', canvasId: 'helena-1', prompt: "Draft a warm reconnection to Helena Garcia framed around the pre-60 milestone, not the rate." },
          { label: 'Run the holistic drill', canvasId: 'helena-2', prompt: "Run the holistic talk-track drill for the Helena Garcia call." },
          { label: 'Something else…', freeform: true },
        ],
      },
    },
  ],
  schedule: [
    {
      id: 'plan',
      time: '8:30 AM',
      title: 'Plan the day · review pipeline',
      body: 'Three open cases, one stalled at NIGO. Helena outreach drafted by Brand Advocate — review and send.',
      status: 'admin',
    },
    {
      id: 'patel',
      time: '11:00 AM',
      duration: '45 MIN',
      title: 'Leela Patel — annual review window opens',
      body:
        'Household grew (second dependent, new home). $1.2M term right-sized to a smaller household — talking points loaded. Cross-sell entry point: education funding.',
      status: 'ready',
      meetingId: 'patel',
    },
    {
      id: 'block',
      time: '1:00 PM',
      duration: '90 MIN',
      title: 'Cross-sell prep · holistic talk-track drill',
      body: 'Strategist queued the Helena prep card. Voice-over rehearsal: 5 min. Run before the call.',
      status: 'needsPrep',
    },
    {
      id: 'wrap',
      time: '4:00 PM',
      title: 'End-of-day wrap',
      body: 'Log Helena outreach. Confirm Patel next-touch on 529 conversation. Flag any new signals.',
      status: 'wrap',
    },
  ],
  signals: [
    {
      id: 'helena-engagement',
      pip: 'green',
      title: 'Helena Garcia — engagement spike on retirement content',
      body: '3 retirement-readiness articles opened in 7 days. Score jumped from 23 → 41. Structural lift, not seasonal.',
      action: 'Lead with curiosity, not the rate. Helena flagged this through her own behavior.',
      badge: { label: 'Opportunity', tone: 'opportunity' },
      defaultOpen: true,
      actionPrompt: "Help me lead Helena with curiosity — not the rate. She flagged retirement readiness through her own behavior.",
      details: {
        analysis: 'Three retirement-content opens in 7 days. Engagement score lift +18 points week-over-week. Articles span Social Security timing, retirement income, and pre-60 planning.',
        insight: 'Structural lift, not seasonal. Helena is doing the homework; she just needs the conversation. The wrong move here is to lead with a rate or a product.',
        recommendation: 'Open with a curiosity question: "I noticed you\'ve been thinking about the next chapter — want to talk through it?" The rate lives at the end of the conversation, not the start.',
        suggestedActions: [
          { label: "Draft the curiosity opener", canvasId: 'helena-2', prompt: "Draft a curiosity-led opening message to Helena Garcia that doesn't mention rates." },
          { label: 'Pull her household profile', canvasId: 'helena-1', prompt: 'Pull Helena Garcia\'s household profile and last 3 touches so I can review before the call.' },
          { label: 'Something else…', freeform: true },
        ],
      },
    },
    {
      id: 'henderson',
      pip: 'amber',
      title: 'Janet Henderson — new address detected',
      body: 'Coastal household in a flood-risk zone. Coverage gap on the new property. 30-day post-move window is open.',
      action: 'Add to this week — review pack queued by Strategist',
      badge: { label: 'Monitor', tone: 'monitor' },
      actionPrompt: "Open the Janet Henderson coverage review — schedule it into this week and load the Strategist's review pack.",
      details: {
        analysis: 'Janet moved 9 days ago to a coastal household in a flood-risk zone. Current term + WL coverage is right-sized for her old property, not the new one.',
        insight: "The 30-day post-move window is the highest-trust moment for a coverage conversation. After day 30, the move loses its emotional weight.",
        recommendation: 'Schedule a 30-minute review this week. Strategist has queued the review pack with flood-risk benchmarks and her household profile.',
        suggestedActions: [
          { label: 'Schedule the review', canvasId: 'janet', prompt: 'Help me find a 30-minute slot for Janet Henderson this week and draft the meeting invite.' },
          { label: 'Open the review pack', canvasId: 'janet', prompt: "Open Janet Henderson's coverage review pack and walk me through the flood-risk benchmarks." },
          { label: 'Something else…', freeform: true },
        ],
      },
    },
    {
      id: 'tom-stall',
      pip: 'red',
      title: 'Tom Anderson — application stalled, day 11',
      body: 'Underwriting hold on a missing APS form. Same pattern as the Maria Diaz case from March.',
      action: 'Resend APS via Sales Central today; this kills momentum on close',
      badge: { label: 'Day 11', tone: 'urgent' },
      actionPrompt: "Walk me through the Tom Anderson stall — same pattern as Maria Diaz in March. Help me resend the APS today.",
    },
  ],
  pace: [
    { label: 'FYC this month',         value: '$2.6K',  sub: 'of $3.5K target',              tone: 'warn' },
    { label: 'Holistic conversations', value: '1 of 2', sub: 'Helena opens the second',      tone: 'good' },
    { label: 'Open cases',             value: '5',      sub: '1 stalled (Anderson)',         tone: 'warn' },
    { label: 'Plan pace',              value: '−18% YoY', sub: 'Helena + Janet recovers it',  tone: 'warn' },
  ],
  autonomous: [
    { id: 'a1', label: 'Drafted Helena reconnection',       meta: 'Brand Advocate · matched your voice',
      actionPrompt: 'Show me the Helena Garcia reconnection draft. I want to review and edit it before it goes out at 10:30.',
      expand: {
        summary: "A warm, milestone-first reconnection drafted in your voice. Frames the pre-60 planning window, not the rate.",
        bullets: [
          'Opens with "Hi Helena — thinking of you as you cross into a new chapter."',
          'No product references · no rate quotes · invites a 20-minute conversation',
          'Suggested call time: 10:30 AM today, with a Tuesday backup',
          'Voice: thoughtful, curious, conservative — matched to your onboarding answers',
        ],
        chips: [
          { label: 'Review the draft', prompt: 'Show me the full Helena Garcia reconnection draft — I want to read it before it goes out.' },
          { label: 'Make it warmer',   prompt: 'Make the Helena reconnection draft warmer and a bit more personal — still my voice.' },
        ],
      },
    },
    { id: 'a2', label: 'Loaded Patel review pack',          meta: 'Intelligence Analyst · cross-sell notes',
      actionPrompt: "Walk me through Leela Patel's annual review pack — what changed in her household, and where the cross-sell notes came from.",
      expand: {
        summary: "Leela's review pack is ready. Household grew (baby #2 in February), term is right-sized to the old household, education gap surfaced.",
        bullets: [
          'Pulled new dependent + address from public records · cross-checked with CRM',
          'Term gap: current $1M, recommended ~$1.8M for new household',
          'Education funding: $18K saved vs. ~$360K target across two kids',
          'Holistic angle: Arjun is not a client — household has half a plan',
        ],
        chips: [
          { label: 'Open the brief', prompt: "Open Leela Patel's pre-meeting brief." },
          { label: 'Draft the right-size pitch', prompt: 'Draft how I should walk Leela through the term right-size — calm, visual, household-first.' },
        ],
      },
    },
    { id: 'a3', label: 'Queued holistic talk-track drill',  meta: 'Coach · 5-min run before 10:30',
      actionPrompt: 'Run the holistic talk-track drill the Coach queued for the Helena call — 5 minutes, role-play.',
      expand: {
        summary: "A 5-minute Coach drill on the holistic talk-track, tuned to a pre-60 milestone conversation. Three roleplay beats.",
        bullets: [
          'Beat 1 · Open with the milestone, not the rate (60 sec)',
          'Beat 2 · One discovery question, then silence (90 sec)',
          'Beat 3 · Land on the "20-minute look" close (90 sec)',
          'Practice tape will be saved and reviewable',
        ],
        chips: [
          { label: 'Start the drill now', prompt: 'Start the 5-minute holistic talk-track drill — pre-60 milestone scenario.' },
          { label: 'Run a shorter version', prompt: 'Give me the 90-second version of the holistic talk-track drill — just the open.' },
        ],
      },
    },
    { id: 'a4', label: 'Flagged Janet flood-risk gap',      meta: 'Signals · review by Friday',
      actionPrompt: "Show me the Janet Henderson flood-risk signal — what triggered it and what the recommended response is by Friday.",
      expand: {
        summary: 'Janet moved to a coastal address in March; FEMA Zone AE flood map shows risk her current household coverage does not address.',
        bullets: [
          'New address change pulled from postal record (Mar 18, 2026)',
          'FEMA cross-check: Zone AE · 1% annual flood probability',
          'Existing Term + WL household covers loss-of-life, not property',
          'Suggested response: 20-min portfolio review against the new household',
        ],
        chips: [
          { label: 'Open the canvas', prompt: "Open the Janet Henderson flood policy opportunity canvas." },
          { label: 'Draft Janet outreach', prompt: 'Draft a warm outreach to Janet Henderson framing a 20-minute portfolio review for the new coastal household.' },
        ],
      },
    },
    { id: 'a5', label: 'Filed yesterday\'s NIGO update',    meta: 'Concierge · case status refreshed',
      actionPrompt: 'Show me yesterday\'s NIGO update — which case, what was outstanding, and what the Concierge did to clear it.',
      expand: {
        summary: "Yesterday's NIGO on the Reyes term app was an SSN format issue. Concierge corrected it overnight and the case is back in queue.",
        bullets: [
          'Issue: SSN entered with dashes — carrier requires unformatted',
          'Resolution: Concierge resubmitted the corrected app at 11:42 PM',
          'Status: back in carrier queue · expected back to UW today',
          'No client-facing impact — Reyes was never notified',
        ],
        chips: [
          { label: 'Show the case file', prompt: 'Pull up the Reyes term application — show me the NIGO history and current status.' },
          { label: 'What else is at risk?', prompt: 'Are any other open applications at risk of going NIGO this week? Show me what to pre-check.' },
        ],
      },
    },
  ],
  whyThisOrder:
    "You said holistic openings and life events matter most. Helena's the rare moment where both line up.",
}

/* ----------------------------------------------------------------------------
 * Jordan R. — cs-building (early career)
 * -------------------------------------------------------------------------- */
const jordan: DailyBriefing = {
  firstName: 'Jordan',
  council: 'No Council yet',
  location: 'Brooklyn NY',
  tenureLabel: 'Year 2 · 71 clients',
  date: { weekday: 'Thu', monthDay: 'May 28' },
  dateLabel: 'Today  |  Thursday, May 28',
  generatedAt: 'Briefing ready · 8:11 AM',
  opportunityToday: {
    fycInPlayLabel: '$1,200 in FYC is one signature away.',
    fycInPlayValue: 1200,
    fycToDateLabel: '$4,800 of $24,000',
    percentToGoal: 20,
    ringNudge: 'Land Nguyen today and you cross 25% — first time this year.',
    streak: 'Activity up 22% this month',
  },
  headline: "Get the Nguyen signature today — your first close of the week is one resend away.",
  headlineHighlight: 'first close of the week',
  summary: '2 items require your attention · 1 prospect call today · 4 follow-ups owed',
  priorities: [
    {
      id: 'nguyen',
      headline: "Nguyen application — DocuSign reminder pending, day 5. Resend before noon.",
      highlight: 'day 5',
      sub: 'Standard send-twice-then-call pattern · est. first commission: $1,400',
      badge: { label: 'Urgent', tone: 'urgent' },
      defaultOpen: true,
      details: {
        analysis:
          "Application complete and submitted. Client hasn't returned the electronic signature — first reminder went out day 2.",
        insight:
          "This is your first close. The send-twice-then-call pattern is your training playbook — don't deviate. Letting it drift past day 7 is where new agents lose first cases.",
        recommendation:
          "Resend the DocuSign reminder, then text Nguyen to confirm receipt. If no signature by EOD, call tomorrow morning.",
        followup: 'Est. first commission: $1,400.',
        suggestedActions: [
          { label: 'Resend the reminder', prompt: "Resend the DocuSign reminder to Nguyen and draft a confirmation text." },
          { label: 'Draft the call script', prompt: "Draft a 90-second call script for the Nguyen follow-up tomorrow morning." },
          { label: 'Something else…', freeform: true },
        ],
      },
    },
    {
      id: 'reyes',
      headline: 'Paul Reyes fact-finding (virtual) at 11:00 AM — referred by M. Rosenthal',
      sub: 'Married, two kids, freelance income · lead with goals, not products',
      badge: { label: 'Prep ready', tone: 'ready' },
      meetingId: 'reyes',
    },
    {
      id: 'momentum',
      headline: 'Your activity is up 22% this month — 11 contacts, 4 fact-finds, 1 close pending',
      sub: 'Above your weekly target three weeks running',
      badge: { label: 'On pace', tone: 'opportunity' },
    },
    {
      id: 'rosenthal',
      headline: 'M. Rosenthal sent two referrals in a month — worth a thank-you',
      sub: 'Brand Advocate drafted a note · review and send before Friday',
      badge: { label: 'Monitor', tone: 'monitor' },
    },
    {
      id: 'drill',
      headline: '4-min retirement-income objection drill loaded for the Reyes call',
      sub: 'Coach pointed at confidence, not pace — based on your onboarding answers',
      badge: { label: 'Need to prep', tone: 'needsPrep' },
    },
  ],
  bottomLine:
    "You're three contacts ahead of your weekly target and one prospect call away from a fact-find this Friday. Your only stuck thread is the Nguyen application — chase the DocuSign reminder before noon. The rest of today is rhythm: four follow-ups, one discovery call at 11.",
  urgent: [
    {
      id: 'nguyen',
      title: 'Nguyen application — DocuSign reminder pending, day 5',
      body:
        "Application complete but client hasn't returned the electronic signature. Standard send-twice-then-call pattern. This is your first close — don't let it drift past day 7.",
      meta: 'Action: Resend DocuSign reminder · Confirm via text · Est. first commission: $1,400',
      badge: { label: 'Urgent', tone: 'urgent' },
    },
  ],
  schedule: [
    {
      id: 'admin',
      time: '8:00 AM',
      title: 'Plan the day · 4 follow-ups owed',
      body: 'Adams (call), Reyes (text), Patel (email), Chen (text). All warm. Brand Advocate drafted three of them — review and send.',
      status: 'admin',
    },
    {
      id: 'reyes',
      time: '11:00 AM',
      duration: '40 MIN',
      title: 'Paul Reyes — fact-finding (virtual)',
      body:
        'Referred by M. Rosenthal. Married, two kids, freelance income. Lead with goals, not products. Confirmed via email yesterday.',
      status: 'ready',
      meetingId: 'reyes',
    },
    {
      id: 'prospecting',
      time: '1:00 PM',
      duration: '90 MIN',
      title: 'Cold outreach block · Coach drilled this with you',
      body: '6 new contacts queued from the warm-warm cohort. Pick 3 and call.',
      status: 'needsPrep',
    },
    {
      id: 'wrap',
      time: '4:00 PM',
      title: 'End-of-day wrap',
      body: 'Log Reyes notes, schedule the follow-up, queue tomorrow.',
      status: 'wrap',
    },
  ],
  signals: [
    {
      id: 'income',
      pip: 'green',
      title: 'Your activity is up 22% this month',
      body: '11 new contacts, 4 fact-finds, 1 close pending. Above your weekly target three weeks running.',
      action: 'Keep the rhythm. Coach will surface a milestone callout at week\'s end.',
      badge: { label: 'On pace', tone: 'opportunity' },
    },
    {
      id: 'rosenthal',
      pip: 'amber',
      title: 'M. Rosenthal — referral source warming',
      body: 'Two referrals in a month from one COI. Worth a thank-you message and a check-in.',
      action: 'Brand Advocate drafted a thank-you · review and send before Friday',
      badge: { label: 'Monitor', tone: 'monitor' },
    },
    {
      id: 'learning',
      pip: 'green',
      title: 'Coach: a 4-min objection drill on retirement-income questions',
      body: 'You flagged confidence as a focus area. The Reyes call this morning may touch retirement income.',
      action: 'Start the 4-min drill now',
      badge: { label: 'Drill', tone: 'opportunity' },
    },
  ],
  pace: [
    { label: 'Weekly contacts',  value: '11 of 8', sub: '+3 ahead of pace',         tone: 'good' },
    { label: 'Fact-finds',       value: '4 of 3',  sub: '+1 ahead',                 tone: 'good' },
    { label: 'Open cases',       value: '3',       sub: '1 awaiting e-sign',        tone: 'warn' },
    { label: 'First-year income',value: '$8.4K',   sub: 'of $18K plan',             tone: 'neutral' },
  ],
  autonomous: [
    { id: 'a1', label: 'Resent Nguyen DocuSign reminder',     meta: 'Concierge · 7:55 AM',
      actionPrompt: 'Show me what was sent to Nguyen on the DocuSign reminder — and whether I should follow up with a text or call.',
      expand: {
        summary: 'Re-sent the DocuSign envelope to Nguyen with a short personalized note. Day 5 of 7 — escalation pattern is ready if needed.',
        bullets: [
          'Email subject: "One more click and your application is done"',
          'Personalized line: "Your wife asked about timing — this is the last step."',
          'If unsigned by EOD: escalate to a personal text from you',
          'If unsigned by Friday: call queued in your morning block',
        ],
        chips: [
          { label: 'Show what was sent', prompt: 'Show me the exact DocuSign reminder that went to Nguyen this morning.' },
          { label: 'Send a personal text now', prompt: "Draft a personal text from me to Nguyen — friendly, gentle, asking if there's anything blocking the signature." },
        ],
      },
    },
    { id: 'a2', label: 'Drafted Adams + Reyes follow-ups',    meta: 'Brand Advocate · review before send',
      actionPrompt: 'Show me the Adams and Reyes follow-up drafts the Brand Advocate prepared. I want to review both before they go.',
      expand: {
        summary: 'Two warm follow-ups drafted in your voice — both wait for your sign-off before sending.',
        bullets: [
          'Adams · call follow-up · references her question about rates · 3 lines',
          'Reyes · pre-meeting confirmation · friendly, no agenda push · 2 lines',
          'Both written conversational + low-pressure — your stated brand voice',
          'Hold-to-send: nothing goes out until you approve',
        ],
        chips: [
          { label: 'Review both drafts', prompt: 'Show me both the Adams and Reyes follow-up drafts side by side.' },
          { label: 'Send them as-is',    prompt: 'Send the Adams and Reyes follow-ups as drafted — no changes.' },
        ],
      },
    },
    { id: 'a3', label: 'Queued 6 contacts for the afternoon', meta: 'Coach · warm-warm cohort',
      actionPrompt: 'Show me the 6 warm contacts the Coach queued for the afternoon — who, why, and the suggested opener for each.',
      expand: {
        summary: '6 warm contacts queued for your 1:00 PM block — all "warm-warm" (no cold calls), each with a written opener.',
        bullets: [
          '3 from referrals · 2 from past events · 1 LinkedIn re-engagement',
          'Average touch effort: 4 minutes per contact',
          "Coach selected for current confidence — none are above your level",
          'Total realistic ask: 2 fact-finders out of 6',
        ],
        chips: [
          { label: 'Show the 6 contacts', prompt: "Walk me through each of the 6 warm contacts in today's afternoon block — who, why, opener." },
          { label: 'Start the block now', prompt: 'Start my prospecting block — guide me through the first contact in the queue.' },
        ],
      },
    },
    { id: 'a4', label: 'Loaded retirement-income drill',      meta: 'Coach · 4 min · for the Reyes call',
      actionPrompt: 'Run the 4-minute retirement-income objection drill loaded for the Paul Reyes call.',
      expand: {
        summary: 'A 4-minute Coach drill on the most common retirement-income objection — "why not just save in my 401(k)?" — tuned for Paul Reyes.',
        bullets: [
          'Beat 1 · Acknowledge the question without defending (60 sec)',
          'Beat 2 · Reframe to risk, not return (90 sec)',
          'Beat 3 · Land the "two buckets" answer (90 sec)',
          'Tape will be saved + reviewable after the call',
        ],
        chips: [
          { label: 'Start the drill', prompt: 'Start the 4-minute retirement-income objection drill — Paul Reyes scenario.' },
          { label: 'Just give me the script', prompt: 'Skip the drill — just give me the 3-beat script for the retirement-income objection.' },
        ],
      },
    },
    { id: 'a5', label: 'Logged yesterday\'s 11 contacts',     meta: 'Concierge · activity refreshed',
      actionPrompt: "Show me yesterday's 11 logged contacts — who they were, what the outcome was, and which need a touch this week.",
      expand: {
        summary: 'Concierge logged yesterday\'s 11 client contacts into the CRM and refreshed your activity counters. You are 22% above weekly target.',
        bullets: [
          '6 calls · 3 texts · 2 in-person · all auto-summarized',
          '4 outcomes need your input — flagged in your follow-up queue',
          'Activity counter: 38/45 weekly target · on pace',
          "Your 3-week streak of >80% target is intact",
        ],
        chips: [
          { label: 'Show the 4 flagged', prompt: 'Pull up the 4 contacts from yesterday that need my input — what they need, what to do next.' },
          { label: "What's my week look like?", prompt: 'Show my activity for this week — what I have hit, what I owe, where I am vs. plan.' },
        ],
      },
    },
  ],
  whyThisOrder:
    "You said the OS should help you keep the rhythm and call out when momentum dips. This week, the rhythm is on — Coach is pointing at confidence, not pace.",
}

export const DAILY_BRIEFING_BY_SEGMENT: Record<SegmentCode, DailyBriefing> = {
  'cs-leading': marcus,
  'hl-accelerating': priya,
  'cs-building': jordan,
}

/* ----------------------------------------------------------------------------
 * Pre-meeting brief — one fully-built example (Emma Clarke, Marcus's flow).
 * Other meetings can drop into a lighter "prep ready" view; this one shows the
 * full Intelligence-Analyst-grade dive Zee's screenshot calls for.
 * -------------------------------------------------------------------------- */

export type PreMeetingBrief = {
  meetingId: string
  segment: SegmentCode
  /* Header */
  title: string
  scheduledLabel: string  /* "Thursday, May 28 · 11:00 AM · In-office · 60 min · Prepared 8:02 AM" */
  durationMin: number
  meetingType: string
  /* Body */
  bottomLine: string
  client: {
    initials: string
    name: string
    age: number
    facts: string[]   /* ["Client since 2012", "3 products", "Last contact: March 14", "Referred Derek Okafor"] */
  }
  productsHeld: { label: string; value: string; warn?: boolean }[]
  household: { label: string; value: string }[]
  needsAttention: {
    id: string
    icon: 'fix' | 'opp' | 'discuss'
    title: string
    body: string
    badge: { label: string; tone: 'urgent' | 'opportunity' | 'discuss' }
  }[]
  talkingPoints: { heading: string; body: string }[]
  landmines: string[]
  decisionToClose: string
}

const emmaClarke: PreMeetingBrief = {
  meetingId: 'clarke',
  segment: 'cs-leading',
  title: 'Emma Clarke — Annual Review',
  scheduledLabel: 'Thursday, May 28 · 11:00 AM · In-office · 60 min · Prepared 8:02 AM',
  durationMin: 60,
  meetingType: 'Annual review',
  bottomLine:
    "Emma is your most engaged multi-product client. This meeting has two jobs: (1) deepen trust by catching the beneficiary gap before she finds it, and (2) open the fee-based planning conversation — she is ready but has not been asked directly.",
  client: {
    initials: 'EC',
    name: 'Emma Clarke',
    age: 52,
    facts: ['Client since 2012', '3 products', 'Last contact: March 14', 'Referred Derek Okafor'],
  },
  productsHeld: [
    { label: 'Whole life (2012)',    value: '$500K · current' },
    { label: 'Term 20 (2018)',       value: '$1M · 14 yrs left' },
    { label: 'Investment acct',      value: '$148K AUM' },
    { label: 'DI coverage',          value: 'None', warn: true },
    { label: 'LTC coverage',         value: 'None', warn: true },
  ],
  household: [
    { label: 'Occupation',    value: 'VP, Healthcare firm' },
    { label: 'Est. HH income',value: '$310K' },
    { label: 'Spouse',        value: 'Michael, 54, self-emp.' },
    { label: 'Children',      value: '2 (ages 17, 14)' },
    { label: 'Est. net worth',value: '$1.1M' },
  ],
  needsAttention: [
    {
      id: 'beneficiary',
      icon: 'fix',
      title: 'Beneficiary on WL policy not updated since 2012',
      body: "Still lists ex-husband as primary beneficiary. This is a compliance and relationship risk. Catch it before she does — this is what a great advisor looks like.",
      badge: { label: 'Fix today', tone: 'urgent' },
    },
    {
      id: 'rollover',
      icon: 'opp',
      title: 'Old 401(k) rollover — $210K sitting at prior employer',
      body: "Identified in last year's review notes. She has not acted. This is the fee-based conversation entry point. The asset is stranded — not invested, not earning, not serving her plan.",
      badge: { label: 'Opportunity', tone: 'opportunity' },
    },
    {
      id: 'college',
      icon: 'discuss',
      title: 'College funding gap — oldest child starts in 14 months',
      body: '529 balance: $44K. Estimated need: $80K+. Conversation last year was deferred. This year it is urgent — the clock is visible now.',
      badge: { label: 'Discuss', tone: 'discuss' },
    },
  ],
  talkingPoints: [
    {
      heading: 'Lead with the beneficiary catch',
      body: '"I flagged something before we start — I want to make sure this is right." This sets the tone as proactive, not reactive. It earns the rest of the meeting.',
    },
    {
      heading: 'Acknowledge the referral',
      body: '"Derek reaching out means a lot." Don\'t dwell — move on.',
    },
    {
      heading: 'Reference the 401(k) directly',
      body: '"We talked about this last March. I\'ve been thinking about it — now feels like the right time." Don\'t ask, offer.',
    },
    {
      heading: 'On college funding: name the number',
      body: '"You have $44K. You need $80K. Here\'s what we can do in 14 months."',
    },
  ],
  landmines: [
    'Michael (spouse) not present and skeptical of fees. Do not close without his buy-in.',
    'Cash pressure from college starting soon. Be sensitive.',
    "DI and LTC are real gaps but not for today — she'll feel sold at.",
  ],
  decisionToClose:
    "Beneficiary update — get the form signed before she leaves. Everything else is conversation opener for follow-up. Don't overload.",
}

const derekOkafor: PreMeetingBrief = {
  meetingId: 'okafor',
  segment: 'cs-leading',
  title: 'Derek Okafor — Prospect discovery',
  scheduledLabel: 'Thursday, May 28 · 2:30 PM · In-office · 60 min · Prepared 8:02 AM',
  durationMin: 60,
  meetingType: 'Discovery',
  bottomLine:
    "Derek is a referral from Emma Clarke — he's verbal-committed but not yet confirmed in writing. This meeting has two jobs: (1) lock the discovery agenda in his calendar before he leaves, and (2) earn the right to a second meeting by listening more than you talk. Term + DI is the obvious entry, but don't lead with product.",
  client: {
    initials: 'DO',
    name: 'Derek Okafor',
    age: 44,
    facts: ['Prospect · first meeting', 'Referred by Emma Clarke', 'Business owner, 12 yrs', 'Verbal confirm only — risk of no-show'],
  },
  productsHeld: [
    { label: 'Life coverage',     value: 'None', warn: true },
    { label: 'Disability income', value: 'None', warn: true },
    { label: 'Business overhead', value: 'None', warn: true },
    { label: 'Retirement plan',   value: 'SEP-IRA · self-managed' },
    { label: 'Investment acct',   value: 'Vanguard · ~$340K (per LinkedIn signal)' },
  ],
  household: [
    { label: 'Occupation',     value: 'Owner, mid-size logistics firm' },
    { label: 'Est. HH income', value: '$420K (variable)' },
    { label: 'Spouse',         value: 'Sarah, 41, part-time educator' },
    { label: 'Children',       value: '3 (ages 11, 9, 6)' },
    { label: 'Est. net worth', value: '$2.4M' },
  ],
  needsAttention: [
    {
      id: 'no-life',
      icon: 'fix',
      title: 'No personal life coverage — 3 kids under 12, business with payroll',
      body: 'The exposure is enormous. Don\'t hard-sell this — the gap will surface in his own answers if you ask the right discovery questions. Let him say it first.',
      badge: { label: 'Listen for', tone: 'urgent' },
    },
    {
      id: 'no-di',
      icon: 'opp',
      title: 'No DI — owner of a service business, sole rainmaker',
      body: "Probably the single most-leveraged product for his profile. If he asks 'what should I have done first?' — this is the honest answer.",
      badge: { label: 'Opportunity', tone: 'opportunity' },
    },
    {
      id: 'business-continuity',
      icon: 'discuss',
      title: 'Business continuity — no buy-sell, no key-person',
      body: '12-year business, 2 partners (LinkedIn). Buy-sell question is the entry point to a much larger conversation. Park it for meeting 2 if today goes well.',
      badge: { label: 'Discuss later', tone: 'discuss' },
    },
  ],
  talkingPoints: [
    {
      heading: 'Confirm the meeting first thing',
      body: 'He was only verbal-committed. The OS sent a calendar invite this morning; confirm acceptance before he sits down. If not accepted, ask in the first 60 seconds.',
    },
    {
      heading: 'Open with Emma',
      body: '"Emma told me a little about you — but I\'d rather hear it from you." This makes the referral feel like a gift, not a setup.',
    },
    {
      heading: 'Ask three questions, then shut up',
      body: '"What does the business look like in five years?" / "What happens to it if you can\'t work for six months?" / "What does Sarah know about how all this is set up?" Don\'t rescue the silence.',
    },
    {
      heading: 'End with a next step, not a pitch',
      body: '"Based on what you\'ve shared, here\'s what I\'d want to look at together — but only if it\'s useful to you. Can we book 45 minutes next week?"',
    },
  ],
  landmines: [
    'Don\'t lead with product. Emma told him "Marcus is different — he asks before he sells." Don\'t break that frame.',
    'His prior advisor (someone at a wirehouse) burned him on a fee discussion. Don\'t raise fees in meeting 1.',
    'Sarah is the household decision-maker for protection conversations. Don\'t close anything she\'s not in the room for.',
  ],
  decisionToClose:
    "Get a second meeting on the calendar before he leaves. Confirm in writing. Don't pitch a product today — your win is earning meeting 2.",
}

const leelaPatel: PreMeetingBrief = {
  meetingId: 'patel',
  segment: 'hl-accelerating',
  title: 'Leela Patel — Annual Review',
  scheduledLabel: 'Thursday, May 28 · 11:00 AM · Virtual · 45 min · Prepared 7:48 AM',
  durationMin: 45,
  meetingType: 'Annual review',
  bottomLine:
    "Leela's household has grown and her current $1.2M term is right-sized to her old household, not her new one. This meeting has two jobs: (1) walk her through what changed and what it means for coverage, and (2) open the education-funding conversation while the new dependent is fresh. She trusts you — don't overcomplicate.",
  client: {
    initials: 'LP',
    name: 'Leela Patel',
    age: 41,
    facts: ['Client since 2018', '2 products', 'Last contact: Feb 9', 'New baby · Feb 2026'],
  },
  productsHeld: [
    { label: 'Term 20 (2018)',  value: '$1M · 12 yrs left', warn: true },
    { label: 'Whole life (2021)', value: '$250K · current' },
    { label: '529 plan',         value: '$18K · child 1 only', warn: true },
    { label: 'Investment acct',  value: '$92K AUM' },
    { label: 'DI coverage',      value: 'Through employer · partial' },
  ],
  household: [
    { label: 'Occupation',     value: 'Senior PM, fintech' },
    { label: 'Est. HH income', value: '$295K' },
    { label: 'Spouse',         value: 'Arjun, 43, software lead' },
    { label: 'Children',       value: '2 (ages 4, 0)' },
    { label: 'Est. net worth', value: '$840K' },
  ],
  needsAttention: [
    {
      id: 'right-size',
      icon: 'fix',
      title: 'Term is right-sized to her old household — second child arrived 3 months ago',
      body: 'The $1M term was modeled for 1 dependent. Recommended need now: ~$1.8M total. This is the conversation she\'s already prepared for — having a new baby raises it for her.',
      badge: { label: 'Right-size today', tone: 'urgent' },
    },
    {
      id: 'edu-funding',
      icon: 'opp',
      title: 'No 529 for the new baby yet · oldest 529 underfunded for the timeline',
      body: 'Open a second 529 today. Reframe oldest 529 contribution against the new 14-year horizon. The math is friendly and the moment is right.',
      badge: { label: 'Opportunity', tone: 'opportunity' },
    },
    {
      id: 'holistic',
      icon: 'discuss',
      title: 'Arjun is not a client yet — household has only half a plan',
      body: "Arjun's coverage is employer-only. He's 43, two kids, primary earner. Frame as a household check, not a sales ask. Suggest a joint conversation later this quarter.",
      badge: { label: 'Discuss', tone: 'discuss' },
    },
  ],
  talkingPoints: [
    {
      heading: 'Lead with the milestone',
      body: '"Before anything else — congratulations on baby #2. How is everyone doing?" Two minutes here earns you the rest of the meeting.',
    },
    {
      heading: 'Walk her through what changed',
      body: '"Your household looks different than it did 12 months ago. Let me show you what your plan looks like next to it." Show the gap visually — don\'t talk her through numbers.',
    },
    {
      heading: 'Name the education number for both kids',
      body: '"For two kids at private + state-flagship blend, you\'re looking at roughly $360K total. You\'re at $18K. Here\'s the monthly that closes the gap by college age." Specific beats vague.',
    },
    {
      heading: 'End with the joint check-in',
      body: '"I\'d love to do a 30-minute household look with you and Arjun in the next month — no pitch, just a picture." Plant the seed for the holistic conversation.',
    },
  ],
  landmines: [
    'Don\'t over-index on permanent life today — she\'s cash-constrained with the new baby. Term right-sizing is the right move.',
    'Arjun has been the slower yes historically. Don\'t pressure for a joint call today — earn it.',
    'Her 529 question last year felt like a sales push (her words). Lead with the gap, not the product.',
  ],
  decisionToClose:
    "Submit the term right-size application today. Open the second 529 enrollment in-meeting. The Arjun conversation is meeting 2 — don't push.",
}

const paulReyes: PreMeetingBrief = {
  meetingId: 'reyes',
  segment: 'cs-building',
  title: 'Paul Reyes — Fact-finding (virtual)',
  scheduledLabel: 'Thursday, May 28 · 11:00 AM · Virtual · 40 min · Prepared 8:11 AM',
  durationMin: 40,
  meetingType: 'Discovery / fact-finding',
  bottomLine:
    "Paul is a warm referral from M. Rosenthal who has now sent you two prospects in a month. This is your first close opportunity of the week — but the way to land it is not to close. Listen. Ask about Lily and the kids. Find the goal he hasn't told anyone yet. Coach has loaded the objection drill for retirement-income — use it.",
  client: {
    initials: 'PR',
    name: 'Paul Reyes',
    age: 38,
    facts: ['Prospect · first meeting', 'Referred by M. Rosenthal', 'Freelance designer · 6 yrs', 'No financial advisor today'],
  },
  productsHeld: [
    { label: 'Life coverage',     value: 'None', warn: true },
    { label: 'Disability income', value: 'None', warn: true },
    { label: 'Retirement plan',   value: 'Solo 401(k) · self-managed' },
    { label: 'Emergency fund',    value: '~$28K (per his words)' },
    { label: 'Health insurance',  value: 'Marketplace · bronze' },
  ],
  household: [
    { label: 'Occupation',     value: 'Freelance designer · 6 yrs' },
    { label: 'Est. HH income', value: '$165K (variable)' },
    { label: 'Spouse',         value: 'Lily, 36, ICU nurse' },
    { label: 'Children',       value: '2 (ages 5, 2)' },
    { label: 'Est. net worth', value: '$310K' },
  ],
  needsAttention: [
    {
      id: 'no-life',
      icon: 'fix',
      title: 'No life coverage — primary earner with two young kids',
      body: 'Term-20 modeled at $1.2M lines up with his profile. Don\'t pitch it today — let him tell you what he wants Lily and the kids to be protected from.',
      badge: { label: 'Listen for', tone: 'urgent' },
    },
    {
      id: 'no-di',
      icon: 'opp',
      title: 'No DI — freelance income · cannot afford a six-month gap',
      body: 'For a freelancer, DI is more existential than life. Lead with the question — "what happens if you can\'t design for six months?" — and let him answer.',
      badge: { label: 'Opportunity', tone: 'opportunity' },
    },
    {
      id: 'roth',
      icon: 'discuss',
      title: 'Solo 401(k) is self-managed — likely under-optimized',
      body: 'Mention it lightly. Don\'t take this on today — it\'s the door to meeting 2 if today goes well.',
      badge: { label: 'Discuss later', tone: 'discuss' },
    },
  ],
  talkingPoints: [
    {
      heading: 'Open with M. Rosenthal',
      body: '"Maria spoke really highly of you — she said your work on her studio rebrand was a turning point." Specific beats generic. He\'ll remember it.',
    },
    {
      heading: 'Three goals questions',
      body: '"What\'s the next big thing for you and Lily?" / "What scares you when you think 10 years out?" / "If you couldn\'t work for six months, what happens?" Don\'t fill the pause after #3.',
    },
    {
      heading: 'Show that you heard him',
      body: '"Here\'s what I think I heard — tell me where I got it wrong." Mirror back his words. This is what wins meeting 2.',
    },
    {
      heading: 'Coach drill — retirement-income objection',
      body: '5 min before the call, run the drill the Coach queued. If he asks "why not just buy term online?" — you\'ll have it ready.',
    },
  ],
  landmines: [
    "Don't pitch product today. Your win is a second meeting and a fact-finder completed.",
    'Maria has told him he can ask hard questions — don\'t get defensive if he does.',
    'He has financial trauma from a parent who lost coverage. Be careful around "what if you couldn\'t work."',
  ],
  decisionToClose:
    "Get a second meeting on the calendar before the call ends. Complete the fact-finder in real time so he sees the whole picture. Don't close anything — meeting 2 is the win.",
}

export const PRE_MEETING_BY_ID: Record<string, PreMeetingBrief> = {
  clarke: emmaClarke,
  okafor: derekOkafor,
  patel: leelaPatel,
  reyes: paulReyes,
}
